# Generated by Django 5.2.8 on 2026-01-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
